package component:hello-world-rust-wasm-component-lib;

/// An example world for the component to target.
world example {
  import print: func(msg: string);

  export say-hi: func();

  export greet: func(name: string) -> string;
  export greet-many: func(names: list<string>) -> string;

  export my-interface: interface {
    resource int-box {
      constructor(a: s32);
      get-value: func() -> s32;
    }
  }
}
