name: ./build.sh
on:
  push:
    branches: "main"
    paths-ignore:
      - hello-world-rust-wasm-component.js/**
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/build.yml"
  pull_request:
    paths-ignore:
      - hello-world-rust-wasm-component.js/**
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/build.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-wasi
      - run: cargo install wasm-tools
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
