name: ./build.sh
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-wasi
      - run: cargo install wasm-tools
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
