name: cargo wasmer
on:
  release:
    types: released
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  cargo-wasmer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup target add wasm32-wasi-preview1-threads
      - uses: wasmerio/setup-wasmer@v3
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-wasmer -y
      - run: cargo binstall wasmer-pack-cli -y
      - run: cargo wasmer
        env:
          WASMER_TOKEN: ${{ secrets.WASMER_TOKEN }}
