name: cargo wasmer --dry-run
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cargo-wasmer-dry-run.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cargo-wasmer-dry-run.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo-wasmer-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup target add wasm32-wasi-preview1-threads
      - uses: wasmerio/setup-wasmer@v3
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-wasmer -y
      - run: cargo binstall wasmer-pack-cli -y
      # Even '--dry-run' still needs token. 🤷‍♀️
      - run: cargo wasmer --dry-run --debug --out-dir=./out
        env:
          WASMER_TOKEN: notatoken
      - run: mv ./out/wasmer.toml ./out/wapm.toml
      - run: wasmer-pack js ./out --out-dir=./out/js
      - uses: actions/upload-artifact@v4
        with:
          name: js
          path: out/js
      - run: wasmer-pack py ./out --out-dir=./out/py
      - uses: actions/upload-artifact@v4
        with:
          name: py
          path: out/py
