name: cargo wasmer --dry-run
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - tests/js/.gitignore
      - .github/**
      - "!.github/workflows/test.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - tests/js/.gitignore
      - .github/**
      - "!.github/workflows/test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup target add wasm32-wasi-preview1-threads
      - uses: wasmerio/setup-wasmer@v3
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-wasmer -y
      - run: cargo binstall wasmer-pack-cli -y
      # Even '--dry-run' still needs token. 🤷‍♀️
      - run: cargo wasmer --dry-run --debug
        env:
          WASMER_TOKEN: notatoken
