name: Draft release
on:
  workflow_dispatch:
jobs:
  draft-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup target add wasm32-wasi
      - run: rustup target add wasm32-wasi-preview1-threads
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-component -y
      - id: get-version
        run: |
          version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - run: cargo component build
      - run: |
          gh release create "$TAG" --draft \
            target/wasm*/release/*.wasm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ steps.get-version.outputs.version }}
