name: Draft release
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yml
  draft-release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: |
          version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - uses: actions/download-artifact@v4
        with:
          name: out
      - run: gh release create "$TAG" --draft out/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ steps.get-version.outputs.version }}
