name: "js: npm test"
on:
  push:
    branches: "main"
    paths:
      - hello-world-rust-wasm-component.js/**
      - .github/workflows/js-npm-test.yml
  pull_request:
    paths:
      - hello-world-rust-wasm-component.js/**
      - .github/workflows/js-npm-test.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
        working-directory: hello-world-rust-wasm-component.js
      - run: npm test
        working-directory: hello-world-rust-wasm-component.js
