name: ./test.sh
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - tests/js/.gitignore
      - .github/**
      - "!.github/workflows/test.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - tests/js/.gitignore
      - .github/**
      - "!.github/workflows/test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wasmerio/setup-wasmer@v3
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-wasmer
      - run: cargo binstall wasmer-pack
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: ./test.sh
